### ISSUE TITLE
maxAlignDistCheck needs to be updated to match the interface for both close and process functions

### ISSUE THREAD

**Issue by ajinkya-pact** [grailbio/doppelmark#1]
` akokate$ go get github.com/grailbio/doppelmark

# github.com/grailbio/doppelmark/markduplicates
/usr/local/opt/go/bin/src/github.com/grailbio/doppelmark/markduplicates/mark_duplicates.go:211:11: cannot use &maxAlignDistCheck literal (type *maxAlignDistCheck) as type bampair.RecordProcessor in return argument:
        *maxAlignDistCheck does not implement bampair.RecordProcessor (wrong type for Close method)
                have Close()
                want Close("github.com/grailbio/bio/encoding/bam".Shard)`

**Comment by yipal** [comment]
Hi, there was a problem with mismatched dependencies.  I have updated the dependencies, and I just 
cloned the doppelmark repo, and ran "go build" and it completed successfully.

The build should work for you now.
